name: Weekly Dad Joke Scraper

on:
  push:
    branches:
      - main
    paths:
      - 'src/dad_joke_scraper.py'
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3
          pip3 install -r src/requirements.txt

      - name: Execute dad_joke_scraper.py
        run: python3 src/dad_joke_scraper.py

      - name: Commit and push if it's not a pull request
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dadjokes.list
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update dadjokes.list" -a
            git push
          fi